name: CI Pipeline 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
env:
  DOTNET_VERSION: '8.0.x'
  
jobs:
  build:
    run-on: ubuntu-latest
    
    steps:
    -uses: actions/checkout@v3
